---
apiVersion: v1
kind: Pod
metadata:
  name: onfailure-restart-pod
spec:
  restartPolicy: OnFailure
  containers:
  - name: c2-onfailure-restart-alpine
    image: alpine
    command: ['sh','-c','sleep 20: dummy command']
