---
apiVersion: v1
kind: Pod
metadata:
  name: readiness-probe
spec:
  containers:
  - name: c1-readiness
    image: k8s.gcr.io/nginx
    livenessProbe:
      httpGet:
        path: /
        port: 9090
      initialDelaySeconds: 3
      periodSeconds: 3
