apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: my-app
    # Remove version: stable here to route traffic to both versions
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
