---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate-deploy
spec:
  template:
    metadata:
      name: recreate-pod
      labels:
        type: recreate
    spec:
      containers:
        - image: nginx:1.27.0-alpine-perl
          name: nginx
  replicas: 4
  selector:
    matchLabels:
      type: recreate
  strategy:
    type: Recreate
